### ISSUE TITLE
"java.lang.ExceptionInInitializerError"

### ISSUE THREAD

**Issue by n0NAA** [LogicTechCorp/NetherEx#216]
When the game was booting up, it apparently crashed, prompting VanillaFix to pop up. Apparently, NetherEx is the main source of this problem. Full report:
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2020-02-17 14:26:55 CST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from NetherEx (netherex)
Caused by: java.lang.ExceptionInInitializerError
    at logictechcorp.netherex.init.NetherExBiomes.registerBiomes(NetherExBiomes.java:87)
    at logictechcorp.netherex.NetherEx.onFMLInitialization(NetherEx.java:111)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ArrayIndexOutOfBoundsException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 692476424 bytes (660 MB) / 2402811904 bytes (2291 MB) up to 3008888832 bytes (2869 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3228m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 74 mods loaded, 74 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                   | Version              | Source                                         | Signature                                |
       |:----- |:-------------------- |:-------------------- |:---------------------------------------------- |:---------------------------------------- |
       | LCHI  | minecraft            | 1.12.2               | minecraft.jar                                  | None                                     |
       | LCHI  | mcp                  | 9.42                 | minecraft.jar                                  | None                                     |
       | LCHI  | FML                  | 8.0.99.99            | forge-1.12.2-14.23.5.2847.jar                  | None                                     |
       | LCHI  | forge                | 14.23.5.2847         | forge-1.12.2-14.23.5.2847.jar                  | None                                     |
       | LCHI  | foamfixcore          | 7.7.4                | minecraft.jar                                  | None                                     |
       | LCHI  | jei                  | 4.15.0.291           | jei_1.12.2-4.15.0.291.jar                      | None                                     |
       | LCHI  | abyssalcraft         | 1.9.16               | AbyssalCraft-1.12.2-1.9.16.jar                 | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCHI  | forgeendertech       | 1.12.2-4.5.0.0       | ForgeEndertech-1.12.2-4.5.0.0-build.0435.jar   | None                                     |
       | LCHI  | adhooks              | 1.12.2-3.2.3.0       | AdHooks-1.12.2-3.2.3.0-build.0435.jar          | None                                     |
       | LCHI  | adlods               | 1.12.2-1.0.7.1       | AdLods-1.12.2-1.0.7.1-build.0441.jar           | None                                     |
       | LCHI  | afraidofthedark      | 1.1.0                | afraidofthedark-1.12.2-1.1.0.jar               | None                                     |
       | LCHI  | aoa3                 | 3.2.4                | AoA3-3.2.4.jar                                 | 8bddeac148843f40e0b9f69201be2f4b3071700d |
       | LCHI  | baubles              | 1.5.2                | Baubles-1.12-1.5.2.jar                         | None                                     |
       | LCHI  | atum                 | 2.0.16               | Atum-1.12.2-2.0.16.jar                         | None                                     |
       | LCHI  | quark                | r1.6-177             | Quark-r1.6-177.jar                             | None                                     |
       | LCHI  | autoreglib           | 1.3-32               | AutoRegLib-1.3-32.jar                          | None                                     |
       | LCHI  | babymobs             | 1.5.5                | BabyMobs-1.12-1.5.5.jar                        | None                                     |
       | LCHI  | betternether         | 0.1.8.6              | betternether-0.1.8.6.jar                       | None                                     |
       | LCHI  | biomesoplenty        | 7.0.1.2441           | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar  | None                                     |
       | LCHI  | bookshelf            | 2.3.590              | Bookshelf-1.12.2-2.3.590.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHI  | bookworm             | 1.12.2-2.3.0         | bookworm-1.12.2-2.3.0.jar                      | None                                     |
       | LCHI  | llibrary             | 1.7.19               | llibrary-1.7.19-1.12.2.jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHI  | cqrepoured           | 1.8.0A               | ChocolateQuestRepoured-1.12.2-1.8.0A.jar       | None                                     |
       | LCHI  | clumps               | 3.1.2                | Clumps-3.1.2.jar                               | None                                     |
       | LCHI  | craftablenametag     | 1.0.0                | CN (MC 1.12.2).jar                             | None                                     |
       | LCHI  | ctm                  | MC1.12.2-1.0.1.30    | CTM-MC1.12.2-1.0.1.30.jar                      | None                                     |
       | LCHI  | darkutils            | 1.8.230              | DarkUtils-1.12.2-1.8.230.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHI  | defiledlands         | 1.4.3                | defiledlands-1.12.2-1.4.3.jar                  | None                                     |
       | LCHI  | dldungeonsjbg        | 1.12.12              | DoomlikeDungeons-1.12.12-MC1.12.2.jar          | None                                     |
       | LCHI  | dungeontactics       | DT-0.16.6            | DungeonTactics-1.12.2-0.16.6.jar               | None                                     |
       | LCHI  | foamfix              | 0.10.10-1.12.2       | foamfix-0.10.10-1.12.2.jar                     | None                                     |
       | LCHI  | galaxite             | 1.1.2                | galaxite-1.1.2-mc1.12.x.jar                    | None                                     |
       | LCHI  | grimoireofgaia       | 1.7.1                | GrimoireOfGaia3-1.12.2-1.7.1.jar               | None                                     |
       | LCHI  | iceandfire           | 1.8.4                | iceandfire-1.8.4.jar                           | None                                     |
       | LCHI  | journeymap           | 1.12.2-5.5.9         | journeymap-1.12.2-5.5.9.jar                    | None                                     |
       | LCHI  | earthenbounty        | 2.1.6                | just_a_few_more_ores-2.1.6.jar                 | None                                     |
       | LCHI  | jeid                 | 1.0.3-48             | JustEnoughIDs-1.0.3-48.jar                     | None                                     |
       | LCHI  | lcrdrfs              | 2.0.0                | LaserCreeperRobotDinoRidersFromSpace-2.0.0.jar | None                                     |
       | LCHI  | libraryex            | 1.0.12               | LibraryEx-1.12.2-1.0.12.jar                    | None                                     |
       | LCHI  | zawa                 | 1.12.2-1.7.0         | zawa-1.12.2-1.7.0.jar                          | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
       | LCHI  | lilcritters          | 1.12.2-0.0.1.3-beta4 | lilcritters-1.12.2-0.0.1.3-beta4.jar           | None                                     |
       | LCHI  | lostcities           | 2.0.22               | lostcities-1.12-2.0.22.jar                     | None                                     |
       | LCHI  | lycanitesmobs        | 2.0.6.4 - MC 1.12.2  | lycanitesmobs-1.12.2-2.0.6.4.jar               | None                                     |
       | LCHI  | mantle               | 1.12-1.3.3.55        | Mantle-1.12-1.3.3.55.jar                       | None                                     |
       | LCHI  | muchmorespiders      | 1.2                  | mmsr-1.0.2-1.12.2.jar                          | None                                     |
       | LCHI  | micwands             | 1.0.4                | MobControlWands_1.12.2-1.0.4.jar               | None                                     |
       | LCHI  | mowziesmobs          | 1.5.4                | mowziesmobs-1.5.4.jar                          | None                                     |
       | LCHI  | faunanatural         | 1.12.2-1.5.0         | NaturalFauna Mod-1.12.2-1.5.0.jar              | None                                     |
       | LCHI  | patchouli            | 1.0-20               | Patchouli-1.0-20.jar                           | None                                     |
       | LCHI  | naturesaura          | 18.1                 | NaturesAura-18.1.jar                           | None                                     |
       | LCHI  | naturescompass       | 1.8.3                | NaturesCompass-1.12.2-1.8.3.jar                | None                                     |
       | LCHE  | netherex             | 2.0.15               | NetherEx-1.12.2-2.0.15.jar                     | None                                     |
       | LCH   | pagamos              | 1.0.0                | pagamos-1.12.2-1.0.0.jar                       | None                                     |
       | LCH   | lambda               | 0.0.2                | ProjectLambda-0.0.2.jar                        | None                                     |
       | LCH   | spartanweaponry      | beta 1.3.8           | SpartanWeaponry-1.12.2-beta-1.3.8.jar          | None                                     |
       | LCH   | spartanfire          | 0.07                 | spartanfire-0.07.jar                           | None                                     |
       | LCH   | spartanshields       | 1.5.4                | SpartanShields-1.12.2-1.5.4.jar                | None                                     |
       | LCH   | surge                | 2.0.77               | Surge-1.12.2-2.0.77.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | takumicraft          | 2.0.0-β.1.6          | takumicraft-1.2.2-2.0.0-beta.1.6.jar           | None                                     |
       | LCH   | texfix               | 4.0                  | TexFix V-1.12-4.0.jar                          | None                                     |
       | LCH   | rt                   | 1.0.0                | The Ultimate Dimension-2.0.2.jar               | None                                     |
       | LCH   | theeightfabledblades | 1.0.0                | TheEightFabledBlades V2.0.01.jar               | None                                     |
       | LCH   | twilightforest       | 3.10.1013            | twilightforest-1.12.2-3.10.1013-universal.jar  | None                                     |
       | LCH   | ultimate_unicorn_mod | 1.5.16               | ultimate_unicorn_mod-1.12.2-1.5.16.jar         | None                                     |
       | LCH   | ultra_amplified_mod  | 4.6.2                | ultra_amplified_mod-1.12.2-4.6.2.jar           | None                                     |
       | LCH   | vanillafix           | 1.0.10-SNAPSHOT      | VanillaFix-1.0.10-99.jar                       | None                                     |
       | LCH   | varietyotextures     | 0.2.1                | varietyotextures-0.2.1.jar                     | None                                     |
       | LCH   | idk                  | 1.0.0                | VPPVu4.jar                                     | None                                     |
       | LCH   | waystones            | 4.1.0                | Waystones_1.12.2-4.1.0.jar                     | None                                     |
       | LCH   | wl                   | 1.0.0                | Wild Lands 2 1.1.jar                           | None                                     |
       | LCH   | yabm                 | 1.0.1                | YABM-1.12.2-1.0.1.jar                          | None                                     |
       | LCH   | zeldamobs            | 2.0                  | Zelda Mobs v2.0 1.12.jar                       | None                                     |
       | LCH   | zildium              | beta-1.0_1.12.2      | zildium-beta-1.0_1.12.2.jar                    | None                                     |
       | LCH   | phosphor-lighting    | 1.12.2-0.2.6         | phosphor-1.12.2-0.2.6+build50-universal.jar    | f0387d288626cc2d937daa504e74af570c52a2f1 |
  Loaded coremods (and transformers): llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      TakumiASMCore (takumicraft-1.2.2-2.0.0-beta.1.6.jar)
                                        com.tntmodders.asm.TakumiASMTransformer
                                      iceandfire (iceandfire-1.8.4.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      CorePlugin (ForgeEndertech-1.12.2-4.5.0.0-build.0435.jar)
                                        
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-48.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 24.20.100.6286' Renderer: 'Intel(R) UHD Graphics 620'
  Suspected Mods: NetherEx (netherex)
  Launched Version: forge-14.23.5.2847
  LWJGL: 2.9.4
  OpenGL: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 24.20.100.6286, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz

**Comment by LogicTechCorp** [comment]
This issue has been fixed in the latest version.
